#!/bin/bash
# Clean out all previous NiCad results
# J.R. Cordy, Queen's University, March 2013

# Revised 1.10.18

if [ "${1}" = "" ]
then
    systems=.
else
    systems="${1}"
fi
    
./scripts/CleanAll "${systems}"

