#!/bin/bash 
# NiCad localization wrapper for Unix-like systems
# J.R. Cordy, Queen"s University, January 2011

# Revised 2.6.20

# Directory where NiCad has been installed
LIB=.

# Now run the appropriate version
$LIB/scripts/NiCadPair $LIB "$1" "$2" "$3" "$4" "$5"

